version: "3.7"
services:
  app:
    image: zerotodev # 우리가 Dockerfile에서 지정했던 app 이름
    ports:
      - 8080:8080
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.4.3
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    container_name: "mongodb"





